[build]
  command = "npm run build"  # Command to build your project
  publish = "build"          # Directory to deploy

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
